apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: receiptsnap-ingress
  namespace: backend-team
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  defaultBackend:
    service:
      name: receiptsnap-backend-svc
      port:
        number: 80